<?php

namespace App\Exports;

use App\Models\SentIncident;
use Illuminate\Contracts\View\View;
use Maatwebsite\Excel\Concerns\FromCollection;
use Maatwebsite\Excel\Concerns\WithHeadings;
use Maatwebsite\Excel\Concerns\WithMapping;

class IncidentExport implements FromCollection, WithHeadings, WithMapping

{
    /**
     * @return \Illuminate\Support\Collection
     */
    protected $start, $end;

    public function __construct($start, $end)
    {
        $this->start = $start;
        $this->end = $end;
    }
    public function collection()
    {
        $query = SentIncident::with(['pers', 'user', 'inspectors'])->select([
            'user_id',
            'stamp_date',
            'shift_date',
            'shift',
            'hse_inspector_id',
            'status_kejadian',
            'tgl_kejadiannya',
            'jam_kejadiannya',
            'lokasi_kejadiannya',
            'klasifikasi_kejadiannya',
            'ada_korban',
            'ada',
            'nama_korban',
            'status',
            'jenis_kelamin',
            'perusahaan_id',
            'bagian',
            'jabatan',
            'masa_kerja',
            'tgl_lahir',
            'jenis_luka_sakit',
            'jenis_luka_sakit2',
            'jenis_luka_sakit3',
            'bagian_tubuh_luka',
            'bagian_tubuh_luka2',
            'bagian_tubuh_luka3',
            'jenis_kejadiannya',
            'penjelasan_kejadiannya',
            'tindakan_pengobatan',
            'tindakan_segera_yang_dilakukan',
            'rincian_dari_pemeriksaan',
            'penyebab_langsung_1_a',
            'penyebab_langsung_1_b',
            'penyebab_langsung_2_a',
            'penyebab_langsung_2_b',
            'penyebab_langsung_3_a',
            'penyebab_langsung_3_b',
            'penyebab_dasar_1_a',
            'penyebab_dasar_1_b',
            'penyebab_dasar_1_c',
            'penyebab_dasar_2_a',
            'penyebab_dasar_2_b',
            'penyebab_dasar_2_c',
            'penyebab_dasar_3_a',
            'penyebab_dasar_3_b',
            'penyebab_dasar_3_c',
            'tindakan_kendali_untuk_peningkatan_1_a',
            'tindakan_kendali_untuk_peningkatan_1_b',
            'tindakan_kendali_untuk_peningkatan_1_c',
            'deskripsi_tindakan_pencegahan_1',
            'pic_1',
            'timing_1',
            'tindakan_kendali_untuk_peningkatan_2_a',
            'tindakan_kendali_untuk_peningkatan_2_b',
            'tindakan_kendali_untuk_peningkatan_2_c',
            'deskripsi_tindakan_pencegahan_2',
            'pic_2',
            'timing_2',
            'tindakan_kendali_untuk_peningkatan_3_a',
            'tindakan_kendali_untuk_peningkatan_3_b',
            'tindakan_kendali_untuk_peningkatan_3_c',
            'deskripsi_tindakan_pencegahan_3',
            'pic_3',
            'timing_3',
            'jml_employee',
            'jml_outsources',
            'jml_security',
            'jml_loading_stacking',
            'jml_contractor',
            'jml_hari_hilang',
            'no_laporan',
            'lta',
            'wlta',
            'trc',
            'total_lta_by_year',
            'total_wlta_by_year',
            'total_work_force',
            'man_hours_per_day',
            'total_man_hours',
            'safe_shift',
            'safe_day',
            'total_safe_day_by_year',
            'total_safe_day_lta2',
            'total_man_hours_lta',
            'total_man_hours_wlta2',
            'safe_shift_wlta',
            'safe_day_wlta',
            'total_safe_day_wlta',

        ]);
        if ($this->start && $this->end) {
            $query->whereBetween('shift_date', [$this->start, $this->end]);
        }

        return $query->orderBy('shift_date', 'asc')->get();
    }

    public function headings(): array
    {
        return [
            'User ID',
            'Penulis',
            'Tanggal Stempel',
            'Tanggal Shift',
            'Shift',
            'ID HSE Inspector',
            'Status Kejadian',
            'Tanggal Kejadian',
            'Jam Kejadian',
            'Lokasi Kejadian',
            'Klasifikasi Kejadian',
            'Ada Korban',
            'Ada',
            'Nama Korban',
            'Status',
            'Jenis Kelamin',
            'Bagian',
            'Jabatan',
            'Masa Kerja',
            'Tanggal Lahir',
            'Jenis Luka Sakit 1',
            'Jenis Luka Sakit 2',
            'Jenis Luka Sakit 3',
            'Bagian Tubuh Luka 1',
            'Bagian Tubuh Luka 2',
            'Bagian Tubuh Luka 3',
            'Jenis Kejadian',
            'Penjelasan Kejadian',
            'Tindakan Pengobatan',
            'Tindakan Segera yang Dilakukan',
            'Rincian Pemeriksaan',
            'Penyebab Langsung 1A',
            'Penyebab Langsung 1B',
            'Penyebab Langsung 2A',
            'Penyebab Langsung 2B',
            'Penyebab Langsung 3A',
            'Penyebab Langsung 3B',
            'Penyebab Dasar 1A',
            'Penyebab Dasar 1B',
            'Penyebab Dasar 1C',
            'Penyebab Dasar 2A',
            'Penyebab Dasar 2B',
            'Penyebab Dasar 2C',
            'Penyebab Dasar 3A',
            'Penyebab Dasar 3B',
            'Penyebab Dasar 3C',
            'Tindakan Kendali 1A',
            'Tindakan Kendali 1B',
            'Tindakan Kendali 1C',
            'Deskripsi Pencegahan 1',
            'PIC 1',
            'Timing 1',
            'Tindakan Kendali 2A',
            'Tindakan Kendali 2B',
            'Tindakan Kendali 2C',
            'Deskripsi Pencegahan 2',
            'PIC 2',
            'Timing 2',
            'Tindakan Kendali 3A',
            'Tindakan Kendali 3B',
            'Tindakan Kendali 3C',
            'Deskripsi Pencegahan 3',
            'PIC 3',
            'Timing 3',
            'Jumlah Employee',
            'Jumlah Outsources',
            'Jumlah Security',
            'Jumlah Loading Stacking',
            'Jumlah Contractor',
            'Jumlah Hari Hilang',
            'Nomor Laporan',
            'LTA',
            'WLTA',
            'TRC',
            'Total LTA by Year',
            'Total WLTA by Year',
            'Total Workforce',
            'Man Hours per Day',
            'Total Man Hours',
            'Safe Shift',
            'Safe Day',
            'Total Safe Day by Year',
            'Total Safe Day LTA2',
            'Total Man Hours LTA',
            'Total Man Hours WLTA2',
            'Safe Shift WLTA',
            'Safe Day WLTA',
            'Total Safe Day WLTA',
        ];
    }


    public function map($row): array
    {
        return [
            $row->user_id,
            $row->user->name,
            $row->stamp_date,
            $row->shift_date,
            $row->shift,
            $row->inspectors->name ?? '-',
            $row->status_kejadian,
            $row->tgl_kejadiannya,
            $row->jam_kejadiannya,
            $row->lokasi_kejadiannya,
            $row->klasifikasi_kejadiannya,
            $row->ada_korban,
            $row->ada,
            $row->nama_korban,
            $row->status,
            $row->jenis_kelamin,
            $row->pers->perusahaan_name ?? '-',
            $row->bagian,
            $row->jabatan,
            $row->masa_kerja,
            $row->tgl_lahir,
            $row->jenis_luka_sakit,
            $row->jenis_luka_sakit2,
            $row->jenis_luka_sakit3,
            $row->bagian_tubuh_luka,
            $row->bagian_tubuh_luka2,
            $row->bagian_tubuh_luka3,
            $row->jenis_kejadiannya,
            $row->penjelasan_kejadiannya,
            $row->tindakan_pengobatan,
            $row->tindakan_segera_yang_dilakukan,
            $row->rincian_dari_pemeriksaan,
            $row->penyebab_langsung_1_a,
            $row->penyebab_langsung_1_b,
            $row->penyebab_langsung_2_a,
            $row->penyebab_langsung_2_b,
            $row->penyebab_langsung_3_a,
            $row->penyebab_langsung_3_b,
            $row->penyebab_dasar_1_a,
            $row->penyebab_dasar_1_b,
            $row->penyebab_dasar_1_c,
            $row->penyebab_dasar_2_a,
            $row->penyebab_dasar_2_b,
            $row->penyebab_dasar_2_c,
            $row->penyebab_dasar_3_a,
            $row->penyebab_dasar_3_b,
            $row->penyebab_dasar_3_c,
            $row->tindakan_kendali_untuk_peningkatan_1_a,
            $row->tindakan_kendali_untuk_peningkatan_1_b,
            $row->tindakan_kendali_untuk_peningkatan_1_c,
            $row->deskripsi_tindakan_pencegahan_1,
            $row->pic_1,
            $row->timing_1,
            $row->tindakan_kendali_untuk_peningkatan_2_a,
            $row->tindakan_kendali_untuk_peningkatan_2_b,
            $row->tindakan_kendali_untuk_peningkatan_2_c,
            $row->deskripsi_tindakan_pencegahan_2,
            $row->pic_2,
            $row->timing_2,
            $row->tindakan_kendali_untuk_peningkatan_3_a,
            $row->tindakan_kendali_untuk_peningkatan_3_b,
            $row->tindakan_kendali_untuk_peningkatan_3_c,
            $row->deskripsi_tindakan_pencegahan_3,
            $row->pic_3,
            $row->timing_3,
            $row->jml_employee,
            $row->jml_outsources,
            $row->jml_security,
            $row->jml_loading_stacking,
            $row->jml_contractor,
            $row->jml_hari_hilang,
            $row->no_laporan,
            $row->lta,
            $row->wlta,
            $row->trc,
            $row->total_lta_by_year,
            $row->total_wlta_by_year,
            $row->total_work_force,
            $row->man_hours_per_day,
            $row->total_man_hours,
            $row->safe_shift,
            $row->safe_day,
            $row->total_safe_day_by_year,
            $row->total_safe_day_lta2,
            $row->total_man_hours_lta,
            $row->total_man_hours_wlta2,
            $row->safe_shift_wlta,
            $row->safe_day_wlta,
            $row->total_safe_day_wlta,

        ];
    }
}
