<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Incident extends Model
{
    use HasFactory;
    protected $table = 'incident_draft';

    // Kolom-kolom yang dapat diisi secara massal
    protected $fillable = [
        'writer',
        'stamp_date',
        'shift_date',
        'shift',
        'safety_officer_1',
        'status_kejadian',
        'tgl_kejadiannya',
        'jam_kejadiannya',
        'lokasi_kejadiannya',
        'klasifikasi_kejadiannya',
        'ada_korban',
        'nama_korban',
        'status',
        'jenis_kelamin',
        'perusahaan',
        'bagian',
        'jabatan',
        'masa_kerja',
        'tgl_lahir',
        'jenis_luka_sakit',
        'jenis_luka_sakit2',
        'jenis_luka_sakit3',
        'bagian_tubuh_luka',
        'bagian_tubuh_luka2',
        'bagian_tubuh_luka3',
        'jenis_kejadiannya',
        'penjelasan_kejadiannya',
        'tindakan_pengobatan',
        'tindakan_segera_yang_dilakukan',
        'rincian_dari_pemeriksaan',
        'penyebab_langsung_1_a',
        'penyebab_langsung_1_b',
        'penyebab_langsung_2_a',
        'penyebab_langsung_2_b',
        'penyebab_langsung_3_a',
        'penyebab_langsung_3_b',
        'penyebab_dasar_1_a',
        'penyebab_dasar_1_b',
        'penyebab_dasar_1_c',
        'penyebab_dasar_2_a',
        'penyebab_dasar_2_b',
        'penyebab_dasar_2_c',
        'penyebab_dasar_3_a',
        'penyebab_dasar_3_b',
        'penyebab_dasar_3_c',
        'tindakan_kendali_untuk_peningkatan_1_a',
        'tindakan_kendali_untuk_peningkatan_1_b',
        'tindakan_kendali_untuk_peningkatan_1_c',
        'deskripsi_tindakan_pencegahan_1',
        'pic_1',
        'timing_1',
        'tindakan_kendali_untuk_peningkatan_2_a',
        'tindakan_kendali_untuk_peningkatan_2_b',
        'tindakan_kendali_untuk_peningkatan_2_c',
        'deskripsi_tindakan_pencegahan_2',
        'pic_2',
        'timing_2',
        'tindakan_kendali_untuk_peningkatan_3_a',
        'tindakan_kendali_untuk_peningkatan_3_b',
        'tindakan_kendali_untuk_peningkatan_3_c',
        'deskripsi_tindakan_pencegahan_3',
        'pic_3',
        'timing_3',
        'jml_employee',
        'jml_outsources',
        'jml_security',
        'jml_loading_stacking',
        'jml_contractor',
        'jml_hari_hilang',
        'bulan_tahun',
        'ada',
        'near_miss',
        'illness_sick',
        'first_aid_case',
        'medical_treatment_case',
        'restricted_work_case',
        'lost_workdays_case',
        'permanent_partial_dissability',
        'permanent_total_dissability',
        'fatality',
        'lta',
        'wlta',
        'trc',
        'fire_incident',
        'road_incident',
        'property_loss_damage',
        'environmental_incident',
        'total_lta_by_year',
        'total_wlta_by_year',
        'total_work_force',
        'man_hours_per_day',
        'total_man_hours',
        'safe_shift',
        'safe_day',

        'total_safe_day_by_year',
        'total_safe_day_lta2',
    ];

    // Tipe data kolom tertentu
    protected $casts = [
        'stamp_date' => 'datetime',
        'shift_date' => 'date',
        'tgl_kejadiannya' => 'date',
        'jam_kejadiannya' => 'datetime:H:i:s',
        'tgl_lahir' => 'date',
        'ada_korban' => 'boolean',
        'ada' => 'boolean',
        'near_miss' => 'boolean',
        'illness_sick' => 'boolean',
        'first_aid_case' => 'boolean',
        'medical_treatment_case' => 'boolean',
        'restricted_work_case' => 'boolean',
        'lost_workdays_case' => 'boolean',
        'permanent_partial_dissability' => 'boolean',
        'permanent_total_dissability' => 'boolean',
        'fatality' => 'boolean',
        'lta' => 'boolean',
        'wlta' => 'boolean',
        'trc' => 'boolean',
        'fire_incident' => 'boolean',
        'road_incident' => 'boolean',
        'property_loss_damage' => 'boolean',
        'environmental_incident' => 'boolean',
        'safe_shift' => 'boolean',
        'safe_day' => 'boolean',
    ];
}
